services:
  - type: web
    name: artisanhcmarketplace-backend
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8080"
      - key: JWT_SECRET
        fromDatabase: false
      - key: RAZORPAY_KEY_ID
        fromDatabase: false
      - key: RAZORPAY_KEY_SECRET
        fromDatabase: false
